movie_list = [
    [1, 9.0, 'Interstellar', True],
    [2, 8.5, 'Fast and the Furious', True],
    [3, 7.0, 'The Dark Knight', False],
    [4, 6.5, 'The Dark Knight Rises', False],
    [5, 6.0, 'The Dark Knight', False],
    [6, 5.5, 'The Dark Knight Rises', False],
    [7, 5.0, 'The Dark Knight', False],
    [8, 4.5, 'The Dark Knight Rises', False],
    [9, 4.0, 'The Dark Knight', True],
    [10, 3.5, 'The Dark Knight Rises', True],
    [11, 3.0, 'The Dark Knight', True],
    [12, 2.5, 'The Dark Knight Rises', True],
    [13, 2.0, 'The Dark Knight', True],
    [14, 1.5, 'The Dark Knight Rises', False],
    [15, 1.0, 'The Dark Knight', False],
    [16, 0.5, 'The Dark Knight Rises', False],
    [17, 0.0, 'The Dark Knight', False],
    [18, 9.0, 'Interstellar', True],
    [19, 8.5, 'Fast and the Furious', True],
    [20, 7.0, 'The Dark Knight', False],
    [21, 6.5, 'The Dark Knight Rises', False],
    [22, 6.0, 'The Dark Knight', False],
    [23, 5.5, 'The Dark Knight Rises', False],
    [24, 5.0, 'The Dark Knight', False],
    [25, 4.5, 'The Dark Knight Rises', False],
    [26, 4.0, 'The Dark Knight', False],
    [27, 3.5, 'The Dark Knight Rises', False],
    [28, 3.0, 'The Dark Knight', False],
    [29, 2.5, 'The Dark Knight Rises', False],
    [30, 2.0, 'The Dark Knight', False],
    [31, 1.5, 'The Dark Knight Rises', False],
    [32, 1.0, 'The Dark Knight', False],
    [33, 0.5, 'The Dark Knight Rises', True],
    [34, 0.0, 'The Dark Knight', True],
    [35, 9.0, 'Interstellar', True],
    [36, 8.5, 'Fast and the Furious', True],
    [37, 7.0, 'The Dark Knight', False],
    [38, 6.5, 'The Dark Knight Rises', False],
    [39, 6.0, 'The Dark Knight', False],
    [40, 5.5, 'The Dark Knight Rises', False],
    [41, 5.0, 'The Dark Knight', False],
]
